add files to homework1
made-ml-in-prod-2021/alinazemlev pull request #2
Opened 2021-05-05 16:49 UTC by alinazemlev

Проект имеет модульную структуру. Есть два варианта configs - для разных типов моделей. Есть отдельный конфиг для логгера. Признаки для моделей создаются с использованием кастомных трансформеров, используются dataclasses.  Скрипт обучения модели в папке project/train, скрипт построения предсказания  - в папке project/predict. Написаны тесты как на отдельные модули, так и на весь пайплан обучения, предсказания. Отчет находится в папке notebooks.

2021-05-06 22:19 UTC, evgerher requested changes
- Лицензию думаю не следует добавлять)
- Новые строки в файлах
- Папка `ml_project`
- Стандарт порядка импортов (base libraries, installed, local), детектируется через pylint
- Переиспользование кода во входных точках программы (train/predict)
- Отсутствие информации по индексации `X[0]`, `X[1]` 
- Папка `.pytest_cache`
- Не всегда ясен смысл тестов
- README, необходимо больше деталей

2021-05-06 22:19 UTC, evgerher commented on project/features/build_features.py
> +        self.params.numerical_cols = features.dtypes[features.dtypes == float].index.values.tolist()
Что если до этого трансформера будет вызван другой и типы потрутся из-за ранее вызванного `LabelEncoder()`?

2021-05-06 22:19 UTC, evgerher commented on project/features/build_features.py
> +                scalier = joblib.load(self.models_params.scaling_path)
`scaler`?

2021-05-06 22:19 UTC, evgerher commented on project/features/build_features.py
> +            X_subset[(X_subset.values < 0)] = 0
А, вот почему все стало бинарным, а не categorical

2021-05-06 22:19 UTC, evgerher commented on project/models/build_model.py
> +        return "/".join(path.split("/")[:-1]) + "/" + name
`path.split("/")` дважды. 

- Да, недорого это делать
- Лучше один раз и иметь отдельные переменные

А еще лучше `path.rsplit("/", 1)`

2021-05-06 22:19 UTC, evgerher commented on project/models/build_model.py
> +        joblib.dump(clf, Model.get_name(prefix, self.models_params.classifier_path_postfix))
Насколько логично, что `fit` works with io and dumps the object state?

2021-05-06 22:19 UTC, evgerher commented on project/predict/predict_model.py
> +setup_logging(LOGGING_YAML)
Не так важно, но обычно видел вызов в `__main__` этого блока

2021-05-06 22:19 UTC, evgerher commented on project/train/train_model.py
> +setup_logging(LOGGING_YAML)
Вот было бы клево переиспользовать подобные блоки кода в train и predict точках входа

2021-05-06 22:19 UTC, evgerher commented on tests/.pytest_cache/README.md
> +# pytest cache directory #
del this folder

2021-05-06 22:19 UTC, evgerher commented on tests/data/test_make_dataset.py
> +    assert len(data) > 10
Сообщение к assert'ам

2021-05-06 22:19 UTC, evgerher commented on tests/data/test_make_dataset.py
> +    assert len(data) > 10
везде

2021-05-06 22:19 UTC, evgerher commented on tests/models/test_build_model.py
> +    assert not model.clf
???

2021-05-06 22:19 UTC, evgerher commented on tests/models/test_build_model.py
> +    assert not model.clf
`assert model is None` это значит ?

2021-05-06 22:22 UTC, evgerher commented
Для EDA могу дополнительно посоветовать `pandas-profiling`, что делает многие вещи за вас: корреляция, распределения, пропуски данных и тд.

2021-05-07 14:07 UTC, alinazemlev commented on project/data/raw/train.csv
> +age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
Для обучения, предсказания фиксированные наборы данных, да. При тестировании работы пайплана и процесса построения фичей используются фейковые, сгенерированные данные.

2021-05-07 14:11 UTC, alinazemlev commented on project/features/build_features.py
> +params = Union[TrainPipelineParams, PredictPipelineParams]
Спасибо, поправила

2021-05-07 14:15 UTC, alinazemlev commented on project/models/build_model.py
> +        return "/".join(path.split("/")[:-1]) + "/" + name
исправила

2021-05-07 14:17 UTC, alinazemlev commented on project/predict/predict_model.py
> +setup_logging(LOGGING_YAML)
да, у меня начались проблемы с импортами на тестах при переносе в __main__. Поэтому оставила пока так.

2021-05-07 14:19 UTC, alinazemlev commented on project/train/train_model.py
> +setup_logging(LOGGING_YAML)
согласна, в следующей версии исправлю.

2021-05-07 14:21 UTC, alinazemlev commented on tests/.pytest_cache/README.md
> +# pytest cache directory #
исправила

2021-05-07 14:31 UTC, alinazemlev commented on tests/models/test_build_model.py
> +    assert not model.clf
Проверка, что  у объекта класса Model был инициализован атрибут clf.

2021-05-07 14:35 UTC, alinazemlev commented on README.md
> +~~~
спасибо, добавлю в следующей версии

2021-05-07 14:39 UTC, alinazemlev commented on project/features/build_features.py
> +        config = yaml.load(open(path, "r"), Loader=yaml.FullLoader)
Вопрос вкуса

2021-05-07 14:56 UTC, alinazemlev commented on project/features/build_features.py
> +        self.params.numerical_cols = features.dtypes[features.dtypes == float].index.values.tolist()
Нет, смысл анализатора колонок в том. что он автоматически определяет типы данных и эту информацию сохраняет в конфиги. Моя вина, что я не положила пустой конфиг с исходным неопределенным полем для фичей. Забыла, исправлю. По второму вопросу - опять же смысл анализатора колонок в том, чтобы он работал с исходными данными.  Получал информацию об исходных распределениях и типах данных, и передавал ее дальше другим трансформерам. Отвечая на Ваш вопрос, логикой программы не предполагается, что до первого транформера может быть вызван другой,  иначе теряется смысл всей конструкции. Но вполне допускается, что после него может быть вызвано все, что угодно.

2021-05-07 14:57 UTC, alinazemlev commented on project/features/build_features.py
> +            return imp.transform(X[1][X[0].numerical_cols])
Согласна, фигня. Надо было использовать именованные списки или мапы, исправлю в следующей версии.

2021-05-07 15:01 UTC, alinazemlev commented on project/features/build_features.py
> +                scalier = joblib.load(self.models_params.scaling_path)
Если Вы про опечатку, то спасибо, исправлю. Если про то зачем оборачивать scaler, когда это трансформер и есть, то в основном для того, чтобы точечно указать какие колонки использовать и сохранить state.  Ну и для единообразия

2021-05-07 15:02 UTC, alinazemlev commented on project/models/build_model.py
> +        joblib.dump(clf, Model.get_name(prefix, self.models_params.classifier_path_postfix))
мм..да, наверное неочень логично. Спасибо

2021-05-07 18:55 UTC, evgerher commented on project/features/build_features.py
> +                scalier = joblib.load(self.models_params.scaling_path)
Это про опечатку :)

2021-05-08 09:51 UTC, evgerher commented on project/features/build_features.py
> +params = Union[TrainPipelineParams, PredictPipelineParams]
Я прошу прощения, был не прав. Не знаю, почему я так решил и ввел вас в заблуждение.
На деле используют скорее CamelCase, никак не CAPS.

2021-05-08 16:01 UTC, evgerher commented on README.md
> +ml_project
Здесь я тоже был не прав.
Неправильно понял этот пункт

2021-05-15 08:51 UTC, goodamigo commented
Папка .ipynb_checkpoints лишняя

2021-05-15 09:20 UTC, goodamigo reviewed
Рекомендуется также исправить замечания @evgerher и провести самооценку (она дает +1 балл)

2021-05-15 09:20 UTC, goodamigo commented on project/features/build_features.py
> +        return X[:, self.get_indexes(X)]
А почему бы не попробовать воспользоваться функцией pandas.DataFrame.dropna

2021-05-15 09:20 UTC, goodamigo commented on project/models/build_model.py
> +        dict_models = {
Я бы это вынес в шапку файла, либо вообще в отдельный файл

2021-05-15 09:20 UTC, goodamigo commented on tests/models/test_build_model.py
> +    params = ModelsParams(
Может лучше параметры сразу как fixture задавать?

2021-05-15 09:20 UTC, goodamigo commented on tests/test_end2end_train.py
> +    assert os.path.exists(params.metric_path)
Хотелось бы протестировать то что модель читается и что-то способна предсказать

2021-05-15 09:20 UTC, goodamigo commented on configs/train_config_logistic.yaml
> +  numerical_cols:
А почему для train конфигов все списки колонок пустые?

2021-05-15 12:51 UTC, alinazemlev commented on project/enities/predict_pipeline_params.py
> +        return schema.load(yaml.safe_load(input_stream))
Есть на этапе построения признаков

2021-05-15 13:24 UTC, alinazemlev commented on project/data/make_dataset.py
> +def split_train_val_data(
Логирование есть в процессе построения фичей в build_features.py

2021-05-15 13:33 UTC, alinazemlev commented on project/features/build_features.py
> +        return X[:, self.get_indexes(X)]
Потому что данный класс используется не для пропущенных  значений, а для фиктивных значений, отсавшихся от других классов в том случае, если каких-то типов переменных обнаружено не было на стадии обучения.

2021-05-15 13:48 UTC, alinazemlev commented on configs/train_config_logistic.yaml
> +  numerical_cols:
Потому что сначала задаются пустые поля, на этапе обучения анализируются типы переменных и информация об этом записывается в prediction config

2021-05-15 14:06 UTC, alinazemlev commented on README.md
> +ml_project
исправила

2021-05-15 14:06 UTC, alinazemlev commented on README.md
> +~~~
исправила

2021-05-15 14:06 UTC, alinazemlev commented on project/features/build_features.py
> +            raise Exception("Column with target not found")
исправила

2021-05-15 14:06 UTC, alinazemlev commented on project/features/build_features.py
> +            return imp.transform(X[1][X[0].numerical_cols])
исправила

2021-05-15 14:06 UTC, alinazemlev commented on project/enities/classifier_params.py
> +class ClassifierParams:
исправила

2021-05-15 14:06 UTC, alinazemlev commented on project/models/build_model.py
> +        dict_models = {
исправила

2021-05-15 14:07 UTC, alinazemlev commented on tests/models/test_build_model.py
> +    params = ModelsParams(
исправила

2021-05-15 14:07 UTC, alinazemlev commented on tests/test_end2end_train.py
> +    assert os.path.exists(params.metric_path)
исправила

2021-05-15 17:16 UTC, goodamigo commented on configs/train_config_logistic.yaml
> +  numerical_cols:
А если захочется задать явно часть переменных как имеющие конкретный тип?

2021-05-15 18:14 UTC, alinazemlev commented on configs/train_config_logistic.yaml
> +  numerical_cols:
Toгда как раз в конфиге можно задать названия переменных в нужных полях и первый трансфомер не использовать. Остальное не поменяется.

2021-05-18 07:27 UTC, goodamigo commented
@alinazemlev когда будете готовы к оценке, запросите еще раз ревью

2021-05-23 17:16 UTC, goodamigo approved these changes
30 баллов

2021-05-24 09:40 UTC, merged